# Generated by Django 2.2 on 2021-04-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotomodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
