# Generated by Django 2.2 on 2021-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photosapp', '0002_auto_20210410_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotomodel',
            name='image',
            field=models.ImageField(upload_to='Photosapp'),
        ),
    ]
